export const products = [
  {
    _id: '1',
    name: 'Airpods Wireless Bluetooth Headphones',
    image: 'images/airpods.jpg',
    description:
      'Stereo headphones that connect to a users cellphone, music player, computer or stereo. Bluetooth headphones may also include a microphone and function as a headset for smartphones, but their primary purpose is music listening',
    brand: 'Apple',
    category: 'Electronics',
    price: 89.99,
    countInStock: 3,
    rating: 4.5,
    numReviews: 4,
  },
  {
    _id: '1',
    name: 'Airpods Wireless Bluetooth Headphones',
    image: 'images/alexa.jpg',
    description:
      'Stereo headphones that connect to a users cellphone, music player, computer or stereo. Bluetooth headphones may also include a microphone and function as a headset for smartphones, but their primary purpose is music listening',
    brand: 'Apple',
    category: 'Electronics',
    price: 89.99,
    countInStock: 3,
    rating: 4.5,
    numReviews: 4,
  },
  {
    _id: '1',
    name: 'Airpods Wireless Bluetooth Headphones',
    image: 'images/camera.jpg',
    description:
      'Stereo headphones that connect to a users cellphone, music player, computer or stereo. Bluetooth headphones may also include a microphone and function as a headset for smartphones, but their primary purpose is music listening',
    brand: 'Apple',
    category: 'Electronics',
    price: 89.99,
    countInStock: 3,
    rating: 4.5,
    numReviews: 4,
  },
  {
    _id: '1',
    name: 'Airpods Wireless Bluetooth Headphones',
    image: 'images/mouse.jpg',
    description:
      'Stereo headphones that connect to a users cellphone, music player, computer or stereo. Bluetooth headphones may also include a microphone and function as a headset for smartphones, but their primary purpose is music listening',
    brand: 'Apple',
    category: 'Electronics',
    price: 89.99,
    countInStock: 3,
    rating: 4.5,
    numReviews: 4,
  },
  {
    _id: '1',
    name: 'Airpods Wireless Bluetooth Headphones',
    image: 'images/phone.jpg',
    description:
      'Stereo headphones that connect to a users cellphone, music player, computer or stereo. Bluetooth headphones may also include a microphone and function as a headset for smartphones, but their primary purpose is music listening',
    brand: 'Apple',
    category: 'Electronics',
    price: 89.99,
    countInStock: 3,
    rating: 4.5,
    numReviews: 4,
  },
  {
    _id: '1',
    name: 'Airpods Wireless Bluetooth Headphones',
    image: 'images/playstation.jpg',
    description:
      'Stereo headphones that connect to a users cellphone, music player, computer or stereo. Bluetooth headphones may also include a microphone and function as a headset for smartphones, but their primary purpose is music listening',
    brand: 'Apple',
    category: 'Electronics',
    price: 89.99,
    countInStock: 3,
    rating: 4.5,
    numReviews: 4,
  },
]
